[package]
authors = ["Eric Kidd <git@randomhacks.net>"]
name = "credentials_to_env"
version = "0.1.0"

[[bin]]
name = "credentials-to-env"

[dependencies]
credentials = "0.2.0"
errno = "0.1.6"
libc = "0.2.8"
